#include "UI/HUD/Panels/WorkOrderEntry.h"
#include "Components/Button.h"
#include "Components/TextBlock.h"

namespace { FString FormatCosts(const TArray<FWorkCost>& Values) { FString R; for (const FWorkCost& V : Values) { if (!R.IsEmpty()) R += TEXT(", "); R += FString::Printf(TEXT("%s x%d"), *(!V.ResourceId.IsNone() ? V.ResourceId.ToString() : V.ItemId.ToString()), V.Amount); } return R.IsEmpty() ? TEXT("No cost") : R; } FString FormatRewards(const TArray<FWorkReward>& Values) { FString R; for (const FWorkReward& V : Values) { if (!R.IsEmpty()) R += TEXT(", "); R += FString::Printf(TEXT("%s x%d"), *(!V.ResourceId.IsNone() ? V.ResourceId.ToString() : V.ItemId.ToString()), V.Amount); } return R; } }
void UWorkOrderEntry::NativeConstruct() { Super::NativeConstruct(); if (Button_Order) { Button_Order->OnPressed.AddDynamic(this, &UWorkOrderEntry::HandleOrderPressed); Button_Order->OnClicked.AddDynamic(this, &UWorkOrderEntry::HandleOrderClicked); } if (Button_AbortOrder) Button_AbortOrder->OnClicked.AddDynamic(this, &UWorkOrderEntry::HandleAbortOrderClicked); }
void UWorkOrderEntry::Setup(const FWorkOrderView& InView) { WorkId=InView.WorkId; CancelRequestId=InView.CancelRequestId; if(Text_Name) Text_Name->SetText(InView.DisplayName); if(Text_Cost) Text_Cost->SetText(FText::FromString(FormatCosts(InView.Costs))); if(Text_Output) Text_Output->SetText(FText::FromString(FormatRewards(InView.Rewards))); if(Text_Status) { FString Status=FString::Printf(TEXT("Queued %d | Active %d"), InView.QueuedCount, InView.ActiveCount); if(InView.ActiveCount>0) Status+=FString::Printf(TEXT(" | Assigned %d/%d"), InView.ActiveWorkerCount, InView.ActiveMaxWorkers); Text_Status->SetText(FText::FromString(Status)); } if(Button_Order) Button_Order->SetIsEnabled(InView.bCanQueue); if(Button_AbortOrder) { Button_AbortOrder->SetIsEnabled(InView.bCanCancel); Button_AbortOrder->SetVisibility(InView.bCanCancel?ESlateVisibility::Visible:ESlateVisibility::Collapsed); } }
void UWorkOrderEntry::HandleOrderPressed() { bOrderPressStartedOnThisEntry = true; }
void UWorkOrderEntry::HandleOrderClicked() { if (!bOrderPressStartedOnThisEntry) { UE_LOG(LogTemp, Warning, TEXT("[WorkUI] Ignored click not pressed on this recipe entry: %s"), *WorkId.ToString()); return; } bOrderPressStartedOnThisEntry = false; OnWorkOrderRequested.Broadcast(WorkId); }
void UWorkOrderEntry::HandleAbortOrderClicked() { if (CancelRequestId != INDEX_NONE) OnWorkOrderAbortRequested.Broadcast(CancelRequestId); }
